# Generated by Django 4.1.7 on 2023-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_content_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(name="product", options={"verbose_name": "ttt"},),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("ggg", "ggg"), ("ddd", "ddd"), ("eee", "eee")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
